name: CI/CD - Branch to QA

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    strategy:
      matrix:
        node-version: [64.x]

    name: CDK build web-api

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout to given branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.deploy_branch }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        run: echo ${{ github.event.inputs.deploy_branch }}
    
